name: hello-world
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: echo "Hello World!"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: sh "ls -ltr"      
   
    
